version: "3.7"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./app:/app

  db:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      TZ: "Asia/Tokyo"
    ports:
      - 15432:5432
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
